{
 "title": "OVMS",
 "time": { "from": "2024-08-27T13:46:51.801Z", "to": "2024-08-28T04:27:34.729Z" },
 "panels": [
  {
   "title": "OVMS Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(ovms_request_time_us_count{interface=\"REST\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OVMS Inference Execution Time ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(ovms_inference_time_us_count[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OVMS Requests Success",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(ovms_requests_success{method=\"ModelInfer\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OVMS Requests Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "rate(ovms_requests_fail[5m])", "legendFormat": "__auto" }
   ]
  }
 ]
}